### ISSUE TITLE
RFC-standard MIBS on Debian / Ubuntu

### ISSUE THREAD

**Issue by tolecnal** [voxpupuli/puppet-snmp#66] opened 2016-04-04 20:49 UTC
Hello,

I saw you had an item listed as an issue in your README, pertaining to RFC-standard MIBS on Debian. If you install the package 'snmp-mibs-downloader' and uncomment the following line in /etc/snmp/snmp.conf:

mibs :

You should now be able to do 'snmpwalk -v 2c -c public localhost system'

This package is available in the following versions of Debian:
- wheezy
- jessie
- sid

Please not however that the package is in the 'non-free' section for Debian packages, and in the 'Multiverse' section for Ubuntu packages.

**Comment by razorsedge** [comment] 2017-04-22 18:34
This is a duplicate of #16. 
I probably will not get around to fixing this without a PR.

**Comment by Dan33l** [comment] 2018-12-13 16:53
closed because of duplicate.
comments will be done on #16

**Closed by Dan33l** 2018-12-13 16:53 UTC
Labels: duplicate, enhancement
